In [3]:
%pip install  scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.9.0-cp313-cp313-macosx_12_0_arm64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in /Users/lezzycan/develop/Data Science/Machine learning/.venv/lib/python3.13/site-packages (from scikit-learn) (2.5.1)
Requirement already satisfied: scipy>=1.10.0 in /Users/lezzycan/develop/Data Science/Machine learning/.venv/lib/python3.13/site-packages (from scikit-learn) (1.18.0)
Collecting joblib>=1.4.0 (from scikit-learn)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting narwhals>=2.0.1 (from scikit-learn)
  Downloading narwhals-2.24.0-py3-none-any.whl.metadata (15 kB)
Collecting threadpoolctl>=3.5.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.9.0-cp313-cp313-macosx_12_0_arm64.whl (8.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.2/8.2 MB 3.5 MB/s  0:00:02 eta 0:00:01
Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading narwhals-2.24.0-py3-none-any.whl (461 kB)
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, narwhals, joblib, scikit-learn
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4/4 [scikit-learn][0m [scikit-learn]
Successfully installed joblib-1.5.3 narwhals-2.24.0 scikit-learn-1.9.0 threadpoolctl-3.6.0

[notice] A new release of pip is available: 25.2 -> 26.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

pd.set_option('display.max_columns', None)

In [3]:
df = pd.read_csv('titanic_dataset.csv')
print("Shape of the dataset:", df.shape)
print("Columns in the dataset:", df.columns.tolist())
df.head()

Shape of the dataset: (891, 15)
Columns in the dataset: ['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare', 'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town', 'alive', 'alone']

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [4]:
# droping "alive" column from the dataset as its redundant with "survived" column

df = df.drop(columns=["alive"])
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,True

##### 1. Drop rows with missing target(safe before train test split)

###### (This is just for demonstration. In this dataset, target column (survived) doesn't have any missing values)

In [5]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alone            0
dtype: int64

In [6]:
target = 'survived'
missing_target_Count = df[target].isna().sum()
print(f"Missing values in target column '{target}': {missing_target_Count}")

# drop the rows that has missing target value

df = df.dropna(subset=[target])
print(f"Shape after dropping missing target rows: {df.shape}")

Missing values in target column 'survived': 0
Shape after dropping missing target rows: (891, 14)

#### 2. Separating features(x) and target(y) variable

In [7]:
X = df.drop(columns = [target])
y = df[target]

In [9]:
X[:5]

,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alone
0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,False
1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,False
2,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,True
3,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,False
4,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,True

In [10]:
y[:5]

0    0
1    1
2    1
3    1
4    0
Name: survived, dtype: int64

In [12]:
print("Target distribution: on full data:")
print(y.value_counts(normalize=True).round(3))

Target distribution: on full data:
survived
0    0.616
1    0.384
Name: proportion, dtype: float64

#### 3. Train-Test Split
 ##### Train set -> ML Model Training
##### X (features) -> training_features (X_train); test_features (X_test)
##### y (target) -> training_targets (y_train); test_labels (y_test)

In [13]:
X_train, X_test , y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y,   # even distribution of target in train and test sets
                                                     )

In [14]:
print("Shapes:")
print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

Shapes:
X_train: (712, 13)
X_test: (179, 13)
y_train: (712,)
y_test: (179,)

In [17]:
train_df = X_train.copy()
train_df[target] = y_train.values


test_df = X_test.copy()
test_df[target] = y_test.values

In [18]:
test_df.head()

,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alone,survived
565,3,male,24.0,2,0,24.1500,S,Third,man,True,NaN,Southampton,False,0
160,3,male,44.0,0,1,16.1000,S,Third,man,True,NaN,Southampton,False,0
553,3,male,22.0,0,0,7.2250,C,Third,man,True,NaN,Cherbourg,True,1
860,3,male,41.0,2,0,14.1083,S,Third,man,True,NaN,Southampton,False,0
241,3,female,NaN,1,0,15.5000,Q,Third,woman,False,NaN,Queenstown,False,1

In [20]:
train_df.to_csv('titanic_train_raw.csv', index=False)
test_df.to_csv('titanic_test_raw.csv', index=False)