In [33]:
##### whenever there is order in features use label encoding

In [59]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import OneHotEncoder, LabelEncoder

In [60]:
train_data = "titanic_train_imputed.csv"
test_data = "titanic_test_imputed.csv"
train_df = pd.read_csv(train_data)
test_df = pd.read_csv(test_data)

target = "survived"
X_train = train_df.drop(columns=target)
y_train = train_df[target]

X_test = test_df.drop(columns = target)
y_test = test_df[target]

print("X Train shape:", X_train.shape)
print("X Test shape:", X_test.shape)

X Train shape: (712, 13)
X Test shape: (179, 13)

In [61]:
X_train.head()

,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alone
0,3,male,28.5,0,0,56.4958,S,Third,man,True,C,Southampton,True
1,2,male,28.5,0,0,0.0000,S,Second,man,True,C,Southampton,True
2,1,male,28.5,0,0,221.7792,S,First,man,True,C,Southampton,True
3,3,female,18.0,0,1,9.3500,S,Third,woman,False,C,Southampton,False
4,2,female,31.0,1,1,26.2500,S,Second,woman,False,C,Southampton,False

In [62]:
# remove redundant columns

X_train = X_train.drop(columns = ["class", "embark_town"])
X_test = X_test.drop(columns = ["class", "embark_town"])

In [63]:
X_train.columns.tolist()

['pclass',
 'sex',
 'age',
 'sibsp',
 'parch',
 'fare',
 'embarked',
 'who',
 'adult_male',
 'deck',
 'alone']

In [64]:
num_cols = X_train.select_dtypes(np.number).columns.to_list()
num_cols

['pclass', 'age', 'sibsp', 'parch', 'fare']

In [65]:
num_cols = ["age", "sibsp", "parch", "fare"]
cat_cols = ["pclass", "sex", "who", "embarked", "adult_male", "deck", "alone"]

In [66]:
binary_ordinal_cols = ["sex", "alone", "adult_male"]
multi_class_nominal_cols = ["embarked", "who", "deck"]

In [67]:
X_train_enc = X_train.copy()
X_test_enc = X_test.copy()

In [68]:
#### Label Encoding
label_encoders = {}

for col in binary_ordinal_cols:
    le = LabelEncoder()
    le.fit(X_train[col])
    label_encoders[col] = le
    X_train_enc[col]= le.transform(X_train[col])
    X_test_enc[col]= le.transform(X_test_enc[col])

In [69]:
X_train_enc.head()

,pclass,sex,age,sibsp,parch,fare,embarked,who,adult_male,deck,alone
0,3,1,28.5,0,0,56.4958,S,man,1,C,1
1,2,1,28.5,0,0,0.0000,S,man,1,C,1
2,1,1,28.5,0,0,221.7792,S,man,1,C,1
3,3,0,18.0,0,1,9.3500,S,woman,0,C,0
4,2,0,31.0,1,1,26.2500,S,woman,0,C,0

#### 7. One Hot encoding

In [70]:
ohe = OneHotEncoder(drop='first', handle_unknown="ignore", sparse_output=False)

In [71]:
ohe.fit(X_train[multi_class_nominal_cols])

OneHotEncoder(drop='first', handle_unknown='ignore', sparse_output=False)

In [72]:
train_ohe = ohe.transform(X_train[multi_class_nominal_cols])
test_ohe = ohe.transform(X_train[multi_class_nominal_cols])

In [73]:
train_ohe

array([[0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 1., ..., 1., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.]], shape=(712, 10))

In [74]:
ohe_cols = ohe.get_feature_names_out(multi_class_nominal_cols)
print(ohe_cols)

['embarked_Q' 'embarked_S' 'who_man' 'who_woman' 'deck_B' 'deck_C'
 'deck_D' 'deck_E' 'deck_F' 'deck_G']

In [75]:
train_ohe = pd.DataFrame(train_ohe, columns = ohe_cols, index = X_train.index)
test_ohe = pd.DataFrame(test_ohe, columns = ohe_cols, index = X_train.index)

In [76]:
train_ohe

,embarked_Q,embarked_S,who_man,who_woman,deck_B,deck_C,deck_D,deck_E,deck_F,deck_G
0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
4,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
707,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
708,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
709,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
710,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
711,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

**Remove original multiclass nominal columns and join the necoded**

In [77]:
X_train_enc = X_train_enc.drop(columns=multi_class_nominal_cols)
X_test_enc = X_test_enc.drop(columns = multi_class_nominal_cols)

In [78]:
X_train_enc = pd.concat([X_train_enc, train_ohe], axis=1)
X_test_enc = pd.concat([X_test_enc, test_ohe], axis=1)

In [79]:
X_train_enc.head()

,pclass,sex,age,sibsp,parch,fare,adult_male,alone,embarked_Q,embarked_S,who_man,who_woman,deck_B,deck_C,deck_D,deck_E,deck_F,deck_G
0,3,1,28.5,0,0,56.4958,1,1,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,2,1,28.5,0,0,0.0000,1,1,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,1,1,28.5,0,0,221.7792,1,1,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,3,0,18.0,0,1,9.3500,0,0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
4,2,0,31.0,1,1,26.2500,0,0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0

In [80]:
X_train_enc.info()

<class 'pandas.DataFrame'>
RangeIndex: 712 entries, 0 to 711
Data columns (total 18 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   pclass      712 non-null    int64
 1   sex         712 non-null    int64
 2   age         712 non-null    float64
 3   sibsp       712 non-null    int64
 4   parch       712 non-null    int64
 5   fare        712 non-null    float64
 6   adult_male  712 non-null    int64
 7   alone       712 non-null    int64
 8   embarked_Q  712 non-null    float64
 9   embarked_S  712 non-null    float64
 10  who_man     712 non-null    float64
 11  who_woman   712 non-null    float64
 12  deck_B      712 non-null    float64
 13  deck_C      712 non-null    float64
 14  deck_D      712 non-null    float64
 15  deck_E      712 non-null    float64
 16  deck_F      712 non-null    float64
 17  deck_G      712 non-null    float64
dtypes: float64(12), int64(6)
memory usage: 100.3 KB

In [ ]:
train_enc_df = X_train_enc.copy()
train_enc_df[target] = y_train.values


test_enc_df = X_test_enc.copy()
#test_enc_df[target] = y_test.values


train_enc_df.to_csv("titanic_train_encoded.csv", index = False)
test_enc_df.to_csv("titanic_test_encoded.csv", index = False)

ValueError: Length of values (179) does not match length of index (712)